# Every registered graph with its licence terms and provenance.
SELECT ?graph ?kind ?identifier ?licence ?redistributable ?inCC0Dump ?precedence ?derivedFrom ?generatedAtTime
WHERE {
  GRAPH ${metadataGraph} {
    ?graph a dim:SourceGraph ;
           dim:graphKind ?kind ;
           dcterms:license ?licence ;
           dim:redistributable ?redistributable ;
           dim:inCC0Dump ?inCC0Dump ;
           dim:precedence ?precedence .
    OPTIONAL { ?graph dcterms:identifier ?identifier }
    OPTIONAL { ?graph prov:wasDerivedFrom ?derivedFrom }
    OPTIONAL { ?graph prov:generatedAtTime ?generatedAtTime }
  }
}
ORDER BY DESC(?precedence) ?graph
